
let words = [
    "honeymoon",
    "yoga",
    "chile",
    "chapstick",
    "justin bieber",
    "skrillex",
    "hair dryer",
    "new year",
    "republican",
    "ruins",
    "ace",
    "ant",
    "arm",
    "ash",
    "axe",
    "bad",
    "bag",
    "bar",
    "bat",
    "bed",
    "bee",
    "bmw",
    "bmx",
    "bow",
    "box",
    "boy",
    "bus",
    "can",
    "cap",
    "cat",
    "cow",
    "cup",
    "cut",
    "day",
    "dew",
    "die",
    "dig",
    "dna",
    "dog",
    "ear",
    "eat",
    "eel",
    "egg",
    "emu",
    "end",
    "eye",
    "flu",
    "fly",
    "fog",
    "fox",
    "fur",
    "gas",
    "gem",
    "god",
    "gru",
    "ham",
    "hat",
    "hen",
    "hop",
    "hot",
    "hug",
    "hut",
    "ice",
    "ivy",
    "jaw",
    "keg",
    "key",
    "kfc",
    "lap",
    "lid",
    "log",
    "low",
    "map",
    "mop",
    "mtv",
    "mud",
    "mug",
    "nun",
    "nut",
    "oar",
    "oil",
    "old",
    "owl",
    "pan",
    "paw",
    "pie",
    "pig",
    "pin",
    "pot",
    "pro",
    "pub",
    "ram",
    "rat",
    "red",
    "rib",
    "rug",
    "run",
    "sad",
    "sea",
    "sew",
    "shy",
    "sit",
    "ski",
    "sky",
    "son",
    "spy",
    "sun",
    "tea",
    "tie",
    "tip",
    "toe",
    "toy",
    "tug",
    "ufo",
    "usb",
    "wax",
    "web",
    "wig",
    "zoo",
    "abba",
    "acid",
    "acne",
    "afro",
    "arch",
    "asia",
    "atom",
    "audi",
    "baby",
    "bait",
    "bald",
    "ball",
    "bank",
    "bark",
    "barn",
    "base",
    "beak",
    "bean",
    "bear",
    "beef",
    "beer",
    "beet",
    "bell",
    "belt",
    "bill",
    "bird",
    "bite",
    "blue",
    "boar",
    "boat",
    "boil",
    "bomb",
    "book",
    "bowl",
    "bull",
    "burp",
    "cage",
    "cake",
    "cape",
    "cash",
    "cast",
    "cave",
    "cell",
    "chef",
    "chew",
    "chin",
    "clap",
    "claw",
    "clay",
    "coal",
    "coat",
    "coin",
    "cola",
    "cold",
    "comb",
    "cone",
    "copy",
    "cord",
    "cork",
    "corn",
    "crab",
    "crow",
    "cuba",
    "cube",
    "cute",
    "dead",
    "deaf",
    "deep",
    "deer",
    "dent",
    "derp",
    "desk",
    "dice",
    "diet",
    "diva",
    "dock",
    "doll",
    "dome",
    "door",
    "dora",
    "dots",
    "drip",
    "drum",
    "duck",
    "duel",
    "east",
    "echo",
    "elmo",
    "elsa",
    "exam",
    "face",
    "fall",
    "farm",
    "fast",
    "fern",
    "finn",
    "fish",
    "fizz",
    "flag",
    "flea",
    "foil",
    "food",
    "fork",
    "fort",
    "frog",
    "full",
    "gang",
    "gasp",
    "gate",
    "germ",
    "gift",
    "girl",
    "glow",
    "glue",
    "goal",
    "goat",
    "gold",
    "golf",
    "good",
    "grid",
    "grin",
    "hair",
    "half",
    "halo",
    "hand",
    "hard",
    "harp",
    "head",
    "heat",
    "heel",
    "hell",
    "hero",
    "hill",
    "hive",
    "hoof",
    "hook",
    "horn",
    "hose",
    "hulk",
    "hurt",
    "idea",
    "ikea",
    "ipad",
    "iron",
    "jail",
    "jayz",
    "jazz",
    "jeep",
    "king",
    "kiss",
    "kite",
    "kiwi",
    "knee",
    "knot",
    "lady",
    "lake",
    "lamb",
    "lamp",
    "lane",
    "lava",
    "leaf",
    "leak",
    "lego",
    "legs",
    "lens",
    "lily",
    "lime",
    "line",
    "link",
    "lion",
    "lips",
    "loaf",
    "lock",
    "logo",
    "loot",
    "love",
    "luck",
    "lung",
    "lynx",
    "maid",
    "mall",
    "mars",
    "mask",
    "maze",
    "meal",
    "meat",
    "melt",
    "meme",
    "milk",
    "mime",
    "mint",
    "mold",
    "mole",
    "monk",
    "moon",
    "moss",
    "moth",
    "nail",
    "nasa",
    "navy",
    "neck",
    "nemo",
    "nerd",
    "nest",
    "nike",
    "noob",
    "nose",
    "nuke",
    "olaf",
    "open",
    "orca",
    "oreo",
    "oval",
    "page",
    "pain",
    "palm",
    "park",
    "path",
    "pear",
    "peas",
    "pike",
    "pill",
    "pine",
    "pink",
    "pipe",
    "plow",
    "plug",
    "poke",
    "polo",
    "pond",
    "pony",
    "poop",
    "poor",
    "pope",
    "pray",
    "puma",
    "punk",
    "race",
    "raft",
    "rail",
    "rain",
    "rake",
    "ramp",
    "read",
    "rest",
    "rice",
    "rick",
    "ring",
    "risk",
    "rock",
    "roll",
    "rome",
    "roof",
    "room",
    "root",
    "rose",
    "ruby",
    "rune",
    "safe",
    "sale",
    "salt",
    "sand",
    "scar",
    "seal",
    "seed",
    "shoe",
    "shop",
    "sick",
    "silo",
    "sing",
    "sink",
    "skin",
    "slam",
    "slow",
    "snow",
    "soap",
    "soda",
    "soil",
    "soup",
    "spin",
    "spit",
    "stab",
    "star",
    "step",
    "swag",
    "swan",
    "taco",
    "tail",
    "tank",
    "tape",
    "taxi",
    "tear",
    "tent",
    "text",
    "thin",
    "thor",
    "thug",
    "tiny",
    "tire",
    "toad",
    "tomb",
    "trap",
    "tree",
    "tuba",
    "tuna",
    "turd",
    "twig",
    "type",
    "undo",
    "vein",
    "vent",
    "vine",
    "vise",
    "vote",
    "walk",
    "wall",
    "warm",
    "wart",
    "wasp",
    "wave",
    "weak",
    "well",
    "west",
    "wife",
    "wind",
    "wine",
    "wing",
    "wire",
    "wolf",
    "wool",
    "work",
    "worm",
    "xbox",
    "yawn",
    "yeti",
    "yoda",
    "yolk",
    "zeus",
    "zoom",
    "zuma",
    "bull,4",
    "reed",
    "abyss",
    "ac/dc",
    "acorn",
    "actor",
    "adult",
    "alarm",
    "alien",
    "alley",
    "angel",
    "angry",
    "anime",
    "anvil",
    "apple",
    "armor",
    "arrow",
    "attic",
    "bacon",
    "bagel",
    "bambi",
    "banjo",
    "beach",
    "belly",
    "below",
    "bench",
    "bible",
    "bingo",
    "birch",
    "black",
    "blimp",
    "blind",
    "blood",
    "blush",
    "board",
    "boots",
    "brain",
    "brand",
    "bread",
    "brick",
    "bride",
    "broom",
    "brush",
    "bulge",
    "bunny",
    "cabin",
    "camel",
    "cello",
    "chain",
    "chair",
    "chalk",
    "cheek",
    "chess",
    "chest",
    "child",
    "chime",
    "china",
    "clean",
    "cliff",
    "climb",
    "cloak",
    "clock",
    "cloth",
    "cloud",
    "clown",
    "coach",
    "coast",
    "cobra",
    "comet",
    "coral",
    "crack",
    "crate",
    "cream",
    "crust",
    "cupid",
    "curry",
    "daisy",
    "dance",
    "darts",
    "demon",
    "dirty",
    "dizzy",
    "dough",
    "drain",
    "drama",
    "dream",
    "dress",
    "drink",
    "drive",
    "drool",
    "dumbo",
    "dwarf",
    "eagle",
    "earth",
    "egypt",
    "elbow",
    "elder",
    "emoji",
    "error",
    "fairy",
    "fanta",
    "fence",
    "field",
    "flash",
    "flask",
    "flock",
    "fluid",
    "flush",
    "flute",
    "frame",
    "fries",
    "frown",
    "fruit",
    "funny",
    "genie",
    "ghost",
    "giant",
    "glass",
    "globe",
    "gloss",
    "glove",
    "gnome",
    "goofy",
    "goose",
    "graph",
    "grass",
    "grave",
    "greed",
    "grill",
    "groom",
    "gummy",
    "hairy",
    "happy",
    "heart",
    "heist",
    "hippo",
    "honey",
    "horse",
    "hotel",
    "house",
    "hyena",
    "india",
    "intel",
    "italy",
    "japan",
    "jeans",
    "jello",
    "jelly",
    "jenga",
    "joker",
    "judge",
    "juice",
    "kazoo",
    "kebab",
    "kirby",
    "kneel",
    "knife",
    "koala",
    "label",
    "laser",
    "lasso",
    "leash",
    "leave",
    "leech",
    "lemon",
    "lemur",
    "limbo",
    "llama",
    "loser",
    "luigi",
    "macho",
    "mafia",
    "magic",
    "magma",
    "mario",
    "match",
    "mayor",
    "melon",
    "messy",
    "metal",
    "miner",
    "model",
    "money",
    "moose",
    "morty",
    "mouse",
    "mouth",
    "movie",
    "mummy",
    "night",
    "ninja",
    "north",
    "notch",
    "novel",
    "nurse",
    "ocean",
    "onion",
    "opera",
    "orbit",
    "organ",
    "otter",
    "paint",
    "panda",
    "pants",
    "paper",
    "paris",
    "party",
    "pasta",
    "patio",
    "pause",
    "peace",
    "peach",
    "pedal",
    "penny",
    "pepsi",
    "petal",
    "piano",
    "pilot",
    "pinky",
    "pizza",
    "plank",
    "plate",
    "pluto",
    "point",
    "poppy",
    "porch",
    "pound",
    "prawn",
    "prism",
    "prune",
    "pumba",
    "purse",
    "queen",
    "queue",
    "quill",
    "quilt",
    "radar",
    "radio",
    "razor",
    "reeds",
    "river",
    "robin",
    "robot",
    "royal",
    "ruler",
    "salad",
    "santa",
    "sauce",
    "sauna",
    "scarf",
    "scary",
    "scent",
    "scoop",
    "score",
    "screw",
    "scuba",
    "shake",
    "shape",
    "shark",
    "sheep",
    "shelf",
    "shell",
    "shirt",
    "shock",
    "short",
    "shout",
    "shrek",
    "shrew",
    "shrub",
    "skull",
    "skunk",
    "skype",
    "sleep",
    "slide",
    "slime",
    "slope",
    "sloth",
    "slump",
    "smell",
    "smile",
    "smoke",
    "snail",
    "snake",
    "socks",
    "sonic",
    "sound",
    "south",
    "space",
    "spade",
    "spain",
    "spark",
    "spear",
    "spine",
    "spool",
    "spoon",
    "spore",
    "squid",
    "stage",
    "stamp",
    "stand",
    "steam",
    "sting",
    "stone",
    "stork",
    "storm",
    "stove",
    "straw",
    "study",
    "sugar",
    "sushi",
    "swamp",
    "swarm",
    "sweat",
    "swing",
    "sword",
    "table",
    "tails",
    "taser",
    "thief",
    "think",
    "thumb",
    "tiger",
    "tired",
    "toast",
    "tooth",
    "torch",
    "totem",
    "touch",
    "towel",
    "tower",
    "train",
    "trend",
    "t-rex",
    "truck",
    "tumor",
    "udder",
    "uncle",
    "vault",
    "venus",
    "video",
    "viola",
    "virus",
    "vodka",
    "vomit",
    "waist",
    "watch",
    "water",
    "whale",
    "wheel",
    "whisk",
    "white",
    "witch",
    "w-lan",
    "world",
    "wound",
    "wrist",
    "xerox",
    "x-ray",
    "yacht",
    "yoshi",
    "young",
    "yo-yo",
    "zebra",
    "zelda",
    "zorro",
    "action",
    "adidas",
    "africa",
    "airbag",
    "almond",
    "alpaca",
    "anchor",
    "anubis",
    "archer",
    "armpit",
    "baboon",
    "badger",
    "bakery",
    "ballet",
    "bamboo",
    "banana",
    "banker",
    "barber",
    "barrel",
    "basket",
    "batman",
    "battle",
    "beanie",
    "beaver",
    "beetle",
    "bellow",
    "betray",
    "bleach",
    "booger",
    "border",
    "bottle",
    "bounce",
    "braces",
    "branch",
    "brazil",
    "breath",
    "bridge",
    "bronze",
    "bruise",
    "bubble",
    "bucket",
    "bullet",
    "bumper",
    "butler",
    "butter",
    "button",
    "cactus",
    "camera",
    "canada",
    "canary",
    "candle",
    "cannon",
    "canyon",
    "carpet",
    "carrot",
    "casino",
    "caviar",
    "cement",
    "cheeks",
    "cheese",
    "cherry",
    "chrome",
    "church",
    "cicada",
    "cinema",
    "circle",
    "circus",
    "clover",
    "cocoon",
    "coffee",
    "coffin",
    "collar",
    "comedy",
    "cookie",
    "copper",
    "corner",
    "corpse",
    "cotton",
    "cousin",
    "cowboy",
    "coyote",
    "crayon",
    "credit",
    "cringe",
    "cruise",
    "cuckoo",
    "cyborg",
    "cymbal",
    "dagger",
    "darwin",
    "desert",
    "dexter",
    "diaper",
    "dinner",
    "doctor",
    "dollar",
    "donkey",
    "double",
    "dragon",
    "drawer",
    "driver",
    "earwax",
    "easter",
    "embers",
    "eminem",
    "engine",
    "eraser",
    "eskimo",
    "europe",
    "fabric",
    "facade",
    "family",
    "farmer",
    "father",
    "faucet",
    "filter",
    "finger",
    "flower",
    "folder",
    "forest",
    "fossil",
    "france",
    "fridge",
    "galaxy",
    "gandhi",
    "garage",
    "garden",
    "garlic",
    "gender",
    "gentle",
    "geyser",
    "goatee",
    "goblin",
    "google",
    "grapes",
    "gravel",
    "greece",
    "grinch",
    "grumpy",
    "guitar",
    "hacker",
    "hammer",
    "handle",
    "hanger",
    "harbor",
    "hawaii",
    "hazard",
    "health",
    "helmet",
    "hermit",
    "hippie",
    "hobbit",
    "hockey",
    "hunger",
    "hunter",
    "hurdle",
    "icicle",
    "impact",
    "insect",
    "inside",
    "iphone",
    "island",
    "israel",
    "jacket",
    "jaguar",
    "jester",
    "juggle",
    "jungle",
    "karate",
    "katana",
    "kermit",
    "kettle",
    "kidney",
    "kitten",
    "knight",
    "kraken",
    "ladder",
    "laptop",
    "lawyer",
    "leader",
    "lizard",
    "london",
    "lotion",
    "lounge",
    "lyrics",
    "magnet",
    "makeup",
    "mantis",
    "marble",
    "market",
    "marmot",
    "mascot",
    "medusa",
    "mexico",
    "minion",
    "minute",
    "mirror",
    "mohawk",
    "monday",
    "monkey",
    "mother",
    "mozart",
    "muffin",
    "muscle",
    "museum",
    "musket",
    "nachos",
    "napkin",
    "nascar",
    "nature",
    "needle",
    "nickel",
    "noodle",
    "norway",
    "nugget",
    "nutmeg",
    "obelix",
    "office",
    "omelet",
    "orange",
    "orchid",
    "oxygen",
    "oyster",
    "paddle",
    "palace",
    "papaya",
    "parade",
    "parrot",
    "pastry",
    "paypal",
    "peanut",
    "pencil",
    "pepper",
    "person",
    "pickle",
    "picnic",
    "pigeon",
    "pigsty",
    "pillar",
    "pillow",
    "pimple",
    "pirate",
    "pistol",
    "plague",
    "planet",
    "player",
    "pocket",
    "poison",
    "poodle",
    "popeye",
    "portal",
    "poster",
    "potato",
    "potion",
    "powder",
    "preach",
    "priest",
    "prince",
    "prison",
    "puddle",
    "puffin",
    "puppet",
    "purity",
    "puzzle",
    "quokka",
    "radish",
    "raisin",
    "rapper",
    "record",
    "reddit",
    "remote",
    "repeat",
    "retail",
    "rewind",
    "ribbon",
    "robber",
    "rocket",
    "rubber",
    "russia",
    "saddle",
    "safari",
    "saliva",
    "salmon",
    "saturn",
    "school",
    "scream",
    "screen",
    "scythe",
    "search",
    "season",
    "second",
    "seesaw",
    "segway",
    "sensei",
    "server",
    "shadow",
    "shovel",
    "shower",
    "silver",
    "skates",
    "skinny",
    "sledge",
    "sleeve",
    "slinky",
    "sneeze",
    "sniper",
    "soccer",
    "socket",
    "sphinx",
    "spider",
    "spiral",
    "sponge",
    "sports",
    "spring",
    "square",
    "statue",
    "stereo",
    "stoned",
    "street",
    "stress",
    "strong",
    "studio",
    "stylus",
    "subway",
    "sudoku",
    "summer",
    "switch",
    "tablet",
    "tailor",
    "tampon",
    "target",
    "tarzan",
    "tattoo",
    "teapot",
    "tennis",
    "tetris",
    "thirst",
    "throat",
    "throne",
    "ticket",
    "tickle",
    "tissue",
    "toilet",
    "tomato",
    "tongue",
    "toucan",
    "tripod",
    "trophy",
    "tunnel",
    "turkey",
    "turnip",
    "turtle",
    "tuxedo",
    "tweety",
    "uranus",
    "vacuum",
    "valley",
    "vanish",
    "victim",
    "violin",
    "vision",
    "volume",
    "voodoo",
    "vortex",
    "waffle",
    "waiter",
    "wall-e",
    "walnut",
    "walrus",
    "wealth",
    "weapon",
    "weasel",
    "welder",
    "wiggle",
    "willow",
    "window",
    "winner",
    "winter",
    "wizard",
    "wreath",
    "wrench",
    "writer",
    "yellow",
    "yogurt",
    "zigzag",
    "zipper",
    "zombie",
    "addida",
    "airport",
    "aladdin",
    "alcohol",
    "allergy",
    "america",
    "android",
    "antenna",
    "anthill",
    "apricot",
    "assault",
    "asterix",
    "athlete",
    "avocado",
    "baklava",
    "balance",
    "balcony",
    "balloon",
    "bandage",
    "bandana",
    "barcode",
    "bathtub",
    "battery",
    "bayonet",
    "bazooka",
    "beatbox",
    "bed bug",
    "bedtime",
    "bicycle",
    "big ben",
    "biology",
    "biscuit",
    "bitcoin",
    "blanket",
    "blender",
    "bobsled",
    "bouncer",
    "bowling",
    "brownie",
    "burglar",
    "burrito",
    "butcher",
    "cabinet",
    "camping",
    "captain",
    "cartoon",
    "catalog",
    "catfish",
    "caveman",
    "ceiling",
    "centaur",
    "charger",
    "cheetah",
    "chicken",
    "chimney",
    "coaster",
    "coconut",
    "compass",
    "concert",
    "console",
    "country",
    "cowbell",
    "creeper",
    "cricket",
    "croatia",
    "crowbar",
    "crystal",
    "cupcake",
    "curtain",
    "cushion",
    "defense",
    "dentist",
    "dessert",
    "diagram",
    "diamond",
    "diploma",
    "discord",
    "disease",
    "dishrag",
    "display",
    "divorce",
    "dolphin",
    "doritos",
    "dracula",
    "droplet",
    "drought",
    "earbuds",
    "eclipse",
    "emerald",
    "england",
    "equator",
    "evening",
    "eyebrow",
    "eyelash",
    "factory",
    "failure",
    "feather",
    "fencing",
    "ferrari",
    "firefly",
    "fireman",
    "florida",
    "florist",
    "fortune",
    "freezer",
    "funeral",
    "gandalf",
    "garbage",
    "germany",
    "giraffe",
    "glasses",
    "glitter",
    "gorilla",
    "gravity",
    "grenade",
    "gumball",
    "haircut",
    "hammock",
    "hamster",
    "harpoon",
    "hashtag",
    "heading",
    "hexagon",
    "highway",
    "hip hop",
    "holiday",
    "horizon",
    "hot dog",
    "husband",
    "iceberg",
    "ireland",
    "janitor",
    "jet ski",
    "journey",
    "karaoke",
    "kendama",
    "ketchup",
    "kitchen",
    "knuckle",
    "kung fu",
    "ladybug",
    "lantern",
    "lasagna",
    "laundry",
    "leather",
    "lettuce",
    "library",
    "lighter",
    "lilypad",
    "loading",
    "lobster",
    "lottery",
    "luggage",
    "machine",
    "mailbox",
    "mailman",
    "mammoth",
    "manatee",
    "manhole",
    "mansion",
    "maracas",
    "massage",
    "meerkat",
    "mercury",
    "mermaid",
    "message",
    "milkman",
    "minivan",
    "missile",
    "monster",
    "morning",
    "mr bean",
    "mustard",
    "narwhal",
    "neptune",
    "network",
    "notepad",
    "nothing",
    "nutella",
    "octagon",
    "octopus",
    "origami",
    "ostrich",
    "outside",
    "pac-man",
    "pajamas",
    "palette",
    "pancake",
    "panther",
    "parents",
    "parking",
    "patient",
    "patrick",
    "patriot",
    "peacock",
    "peasant",
    "pelican",
    "penguin",
    "perfume",
    "picasso",
    "pickaxe",
    "pikachu",
    "pinball",
    "plumber",
    "plunger",
    "pokemon",
    "popcorn",
    "popular",
    "present",
    "pretzel",
    "printer",
    "protest",
    "provoke",
    "pudding",
    "pumpkin",
    "pyramid",
    "quarter",
    "raccoon",
    "racecar",
    "rainbow",
    "ravioli",
    "reality",
    "referee",
    "reptile",
    "romania",
    "rooster",
    "samsung",
    "sandbox",
    "sausage",
    "science",
    "seafood",
    "seagull",
    "seasick",
    "seaweed",
    "shallow",
    "shampoo",
    "shoebox",
    "shotgun",
    "silence",
    "skyline",
    "snowman",
    "soldier",
    "spatula",
    "speaker",
    "spinach",
    "spoiler",
    "stadium",
    "stapler",
    "stomach",
    "student",
    "sunburn",
    "sunrise",
    "surface",
    "surgeon",
    "sweater",
    "tadpole",
    "teacher",
    "thunder",
    "timpani",
    "titanic",
    "toaster",
    "toenail",
    "toolbox",
    "top hat",
    "tornado",
    "torpedo",
    "tourist",
    "tractor",
    "traffic",
    "trailer",
    "trigger",
    "trumpet",
    "twitter",
    "ukulele",
    "unibrow",
    "unicorn",
    "uniform",
    "upgrade",
    "vaccine",
    "vampire",
    "vanilla",
    "vatican",
    "victory",
    "village",
    "villain",
    "vinegar",
    "vitamin",
    "vlogger",
    "volcano",
    "vulture",
    "wake up",
    "weather",
    "website",
    "wedding",
    "western",
    "whisper",
    "whistle",
    "wingnut",
    "witness",
    "wrinkle",
    "youtube",
    "zipline",
    "abstract",
    "accident",
    "addition",
    "adorable",
    "aircraft",
    "airplane",
    "anaconda",
    "anteater",
    "antelope",
    "applause",
    "aquarium",
    "assassin",
    "asteroid",
    "atlantis",
    "audience",
    "backbone",
    "backflip",
    "backpack",
    "bagpipes",
    "baguette",
    "band-aid",
    "barbecue",
    "basement",
    "bathroom",
    "bean bag",
    "birthday",
    "blizzard",
    "blowfish",
    "bookmark",
    "bracelet",
    "broccoli",
    "brunette",
    "building",
    "bunk bed",
    "bus stop",
    "calendar",
    "campfire",
    "canister",
    "car wash",
    "carnival",
    "catapult",
    "cauldron",
    "cerberus",
    "chainsaw",
    "champion",
    "chemical",
    "chestnut",
    "clarinet",
    "cocktail",
    "collapse",
    "comedian",
    "complete",
    "computer",
    "confused",
    "corn dog",
    "crossbow",
    "crucible",
    "cucumber",
    "cupboard",
    "customer",
    "cylinder",
    "dandruff",
    "daughter",
    "deadpool",
    "delivery",
    "detonate",
    "diagonal",
    "dinosaur",
    "disaster",
    "distance",
    "doghouse",
    "dominoes",
    "doorknob",
    "download",
    "drum kit",
    "dynamite",
    "eggplant",
    "einstein",
    "election",
    "elephant",
    "elevator",
    "employer",
    "engineer",
    "espresso",
    "exercise",
    "fabulous",
    "facebook",
    "festival",
    "figurine",
    "fireball",
    "fireside",
    "firework",
    "flagpole",
    "flamingo",
    "forehead",
    "fortress",
    "fountain",
    "freckles",
    "frosting",
    "gangster",
    "gardener",
    "garfield",
    "gas mask",
    "gasoline",
    "goldfish",
    "graffiti",
    "handicap",
    "hard hat",
    "hay bale",
    "hazelnut",
    "headache",
    "headband",
    "hedgehog",
    "hercules",
    "homeless",
    "hospital",
    "industry",
    "infinite",
    "insomnia",
    "internet",
    "invasion",
    "iron man",
    "jalapeno",
    "kangaroo",
    "keyboard",
    "landlord",
    "language",
    "lemonade",
    "levitate",
    "licorice",
    "lipstick",
    "lollipop",
    "macaroni",
    "magazine",
    "magician",
    "manicure",
    "marathon",
    "marigold",
    "matchbox",
    "mattress",
    "meatball",
    "meatloaf",
    "mechanic",
    "mercedes",
    "midnight",
    "military",
    "miniclip",
    "minigolf",
    "minotaur",
    "mosquito",
    "mothball",
    "mountain",
    "mr. bean",
    "murderer",
    "mushroom",
    "mustache",
    "neighbor",
    "nostrils",
    "notebook",
    "nutshell",
    "panpipes",
    "parakeet",
    "password",
    "pavement",
    "pendulum",
    "pet food",
    "pet shop",
    "pinwheel",
    "platypus",
    "ponytail",
    "popsicle",
    "portrait",
    "portugal",
    "poseidon",
    "positive",
    "postcard",
    "pregnant",
    "princess",
    "pringles",
    "raincoat",
    "raindrop",
    "reindeer",
    "religion",
    "revolver",
    "ringtone",
    "rockstar",
    "sailboat",
    "sandwich",
    "scissors",
    "scotland",
    "scribble",
    "sea lion",
    "seahorse",
    "seashell",
    "security",
    "shoelace",
    "shopping",
    "shoulder",
    "six pack",
    "skeleton",
    "ski jump",
    "skittles",
    "skrillex",
    "slippery",
    "snowball",
    "sombrero",
    "sparkles",
    "squirrel",
    "starfish",
    "stingray",
    "streamer",
    "suitcase",
    "sunshade",
    "superman",
    "survivor",
    "swimsuit",
    "symphony",
    "tabletop",
    "take off",
    "teaspoon",
    "tentacle",
    "tiramisu",
    "tortoise",
    "trapdoor",
    "traveler",
    "treasure",
    "triangle",
    "tricycle",
    "triplets",
    "trombone",
    "tropical",
    "umbrella",
    "unicycle",
    "universe",
    "vacation",
    "vertical",
    "violence",
    "vuvuzela",
    "werewolf",
    "whatsapp",
    "windmill",
    "wireless",
    "wrapping",
    "wrestler",
    "yearbook",
    "youtuber",
    "zeppelin",
    "accordion",
    "addiction",
    "afterlife",
    "albatross",
    "alligator",
    "ambulance",
    "amsterdam",
    "animation",
    "antivirus",
    "apartment",
    "apple pie",
    "architect",
    "argentina",
    "armadillo",
    "astronaut",
    "asymmetry",
    "australia",
    "autograph",
    "back pain",
    "ballerina",
    "barbarian",
    "bartender",
    "beanstalk",
    "bear trap",
    "bed sheet",
    "beethoven",
    "billiards",
    "bird bath",
    "blindfold",
    "blueberry",
    "bodyguard",
    "bomberman",
    "bookshelf",
    "boomerang",
    "brainwash",
    "breakfast",
    "broadcast",
    "bruce lee",
    "bulldozer",
    "butterfly",
    "capricorn",
    "cardboard",
    "carnivore",
    "carpenter",
    "cat woman",
    "cathedral",
    "celebrate",
    "celebrity",
    "centipede",
    "chameleon",
    "champagne",
    "chewbacca",
    "chihuahua",
    "chinatown",
    "chocolate",
    "christmas",
    "cigarette",
    "classroom",
    "clickbait",
    "clownfish",
    "cockroach",
    "colosseum",
    "commander",
    "communism",
    "community",
    "condiment",
    "continent",
    "corkscrew",
    "cornfield",
    "crocodile",
    "croissant",
    "dalmatian",
    "dandelion",
    "dashboard",
    "deodorant",
    "depressed",
    "desperate",
    "detective",
    "dispenser",
    "dollhouse",
    "dragonfly",
    "duct tape",
    "elon musk",
    "evaporate",
    "evolution",
    "excalibur",
    "excavator",
    "explosion",
    "eyeshadow",
    "fast food",
    "filmmaker",
    "fingertip",
    "firehouse",
    "fireplace",
    "fireproof",
    "fish bowl",
    "fisherman",
    "frostbite",
    "full moon",
    "furniture",
    "generator",
    "gentleman",
    "geography",
    "gladiator",
    "glowstick",
    "godfather",
    "golf cart",
    "graveyard",
    "hairbrush",
    "hairspray",
    "hamburger",
    "handshake",
    "harmonica",
    "headboard",
    "hibernate",
    "high five",
    "hilarious",
    "hollywood",
    "honeycomb",
    "hopscotch",
    "horsewhip",
    "hot sauce",
    "hourglass",
    "hula hoop",
    "hypnotize",
    "ice cream",
    "incognito",
    "injection",
    "interview",
    "invention",
    "invisible",
    "jellyfish",
    "john cena",
    "jump rope",
    "junk food",
    "king kong",
    "lady gaga",
    "landscape",
    "las vegas",
    "lava lamp",
    "librarian",
    "lightbulb",
    "lightning",
    "limousine",
    "lion king",
    "magnifier",
    "mannequin",
    "margarine",
    "marmalade",
    "mcdonalds",
    "megaphone",
    "meteorite",
    "microsoft",
    "microwave",
    "milkshake",
    "milky way",
    "minecraft",
    "mona lisa",
    "motorbike",
    "mousetrap",
    "nail file",
    "newspaper",
    "nightclub",
    "nightmare",
    "nose hair",
    "nose ring",
    "nosebleed",
    "orangutan",
    "orchestra",
    "paintball",
    "palm tree",
    "paper bag",
    "parachute",
    "peninsula",
    "pensioner",
    "peppa pig",
    "pepperoni",
    "periscope",
    "photoshop",
    "pine cone",
    "pineapple",
    "pinocchio",
    "pistachio",
    "pitchfork",
    "poisonous",
    "policeman",
    "pollution",
    "porcupine",
    "porky pig",
    "president",
    "price tag",
    "professor",
    "promotion",
    "quicksand",
    "radiation",
    "raspberry",
    "reception",
    "rectangle",
    "recycling",
    "roadblock",
    "saltwater",
    "sandstorm",
    "satellite",
    "saxophone",
    "scarecrow",
    "scientist",
    "sculpture",
    "seat belt",
    "shipwreck",
    "signature",
    "singapore",
    "skydiving",
    "slingshot",
    "snowboard",
    "snowflake",
    "spaceship",
    "spaghetti",
    "spartacus",
    "spelunker",
    "spiderman",
    "spongebob",
    "sprinkler",
    "squidward",
    "star wars",
    "starfruit",
    "stone age",
    "stop sign",
    "submarine",
    "sunflower",
    "surfboard",
    "swordfish",
    "tangerine",
    "tarantula",
    "telephone",
    "telescope",
    "teletubby",
    "tombstone",
    "toothpick",
    "tow truck",
    "translate",
    "trash can",
    "treadmill",
    "treehouse",
    "vault boy",
    "vegetable",
    "wallpaper",
    "warehouse",
    "water gun",
    "waterfall",
    "wolverine",
    "workplace",
    "wrestling",
    "xylophone",
    "yardstick",
    "shoulders",
    "anglerfish",
    "antarctica",
    "apocalypse",
    "apple seed",
    "aristocrat",
    "basketball",
    "battleship",
    "bill gates",
    "binoculars",
    "black hole",
    "blackberry",
    "blacksmith",
    "bricklayer",
    "broomstick",
    "bubble gum",
    "bugs bunny",
    "bus driver",
    "cab driver",
    "can opener",
    "cappuccino",
    "cell phone",
    "chandelier",
    "cheesecake",
    "chest hair",
    "chestplate",
    "chimpanzee",
    "chinchilla",
    "chopsticks",
    "comic book",
    "commercial",
    "controller",
    "cookie jar",
    "coral reef",
    "daffy duck",
    "dictionary",
    "diss track",
    "earthquake",
    "face paint",
    "fake teeth",
    "family guy",
    "fingernail",
    "fire alarm",
    "fire truck",
    "fist fight",
    "flashlight",
    "floodlight",
    "flying pig",
    "glue stick",
    "gold chain",
    "golden egg",
    "graduation",
    "grapefruit",
    "great wall",
    "guillotine",
    "guinea pig",
    "gummy bear",
    "gummy worm",
    "happy meal",
    "headphones",
    "helicopter",
    "hieroglyph",
    "high heels",
    "high score",
    "hitchhiker",
    "home alone",
    "hovercraft",
    "iron giant",
    "jackhammer",
    "james bond",
    "journalist",
    "katy perry",
    "laboratory",
    "lawn mower",
    "leprechaun",
    "lighthouse",
    "lightsaber",
    "litter box",
    "london eye",
    "lumberjack",
    "madagascar",
    "magic wand",
    "mayonnaise",
    "microphone",
    "microscope",
    "mont blanc",
    "morse code",
    "motorcycle",
    "nutcracker",
    "overweight",
    "pharmacist",
    "photograph",
    "piggy bank",
    "playground",
    "pogo stick",
    "polar bear",
    "programmer",
    "punishment",
    "rainforest",
    "razorblade",
    "red carpet",
    "reflection",
    "restaurant",
    "rhinoceros",
    "robin hood",
    "scooby doo",
    "semicircle",
    "silverware",
    "skateboard",
    "skribbl.io",
    "skyscraper",
    "space suit",
    "steve jobs",
    "strawberry",
    "suez canal",
    "sunglasses",
    "superpower",
    "tablecloth",
    "teddy bear",
    "television",
    "terminator",
    "tissue box",
    "toothbrush",
    "toothpaste",
    "trick shot",
    "usain bolt",
    "vegetarian",
    "video game",
    "vin diesel",
    "volleyball",
    "windshield",
    "wine glass",
    "wonderland",
    "woodpecker",
    "angry birds",
    "barbed wire",
    "bell pepper",
    "bottle flip",
    "butt cheeks",
    "caterpillar",
    "cauliflower",
    "ceiling fan",
    "cheerleader",
    "coast guard",
    "coffee shop",
    "color-blind",
    "comfortable",
    "crawl space",
    "credit card",
    "donald duck",
    "electrician",
    "electricity",
    "firecracker",
    "firefighter",
    "floppy disk",
    "fly swatter",
    "forest fire",
    "grandmother",
    "grasshopper",
    "gravedigger",
    "hair roller",
    "hello kitty",
    "hummingbird",
    "imagination",
    "jackie chan",
    "kim jong-un",
    "magic trick",
    "marshmallow",
    "motherboard",
    "mr meeseeks",
    "nail polish",
    "netherlands",
    "new zealand",
    "north korea",
    "observatory",
    "pencil case",
    "photo frame",
    "pirate ship",
    "playstation",
    "pot of gold",
    "sand castle",
    "spray paint",
    "stegosaurus",
    "supermarket",
    "talent show",
    "taxi driver",
    "temperature",
    "the beatles",
    "thermometer",
    "tooth fairy",
    "underground",
    "underweight",
    "water cycle",
    "wheelbarrow",
    "barack obama",
    "bart simpson",
    "belly button",
    "black friday",
    "broken heart",
    "cheeseburger",
    "chuck norris",
    "conversation",
    "cotton candy",
    "donald trump",
    "easter bunny",
    "eiffel tower",
    "electric car",
    "fast forward",
    "fire hydrant",
    "flamethrower",
    "frankenstein",
    "golden apple",
    "harry potter",
    "intersection",
    "jesus christ",
    "johnny bravo",
    "kindergarten",
    "mickey mouse",
    "mr. meeseeks",
    "neighborhood",
    "notification",
    "photographer",
    "pillow fight",
    "pink panther",
    "receptionist",
    "relationship",
    "skateboarder",
    "sledgehammer",
    "social media",
    "solar system",
    "table tennis",
    "thunderstorm",
    "time machine",
    "tower bridge",
    "truck driver",
    "velociraptor",
    "veterinarian",
    "wonder woman",
    "yin and yang",
    "advertisement",
    "archaeologist",
    "demonstration",
    "finn and jake",
    "green lantern",
    "homer simpson",
    "hot chocolate",
    "jimmy neutron",
    "mount everest",
    "robbie rotten",
    "shaving cream",
    "shopping cart",
    "swimming pool",
    "tennis racket",
    "tower of pisa",
    "traffic light",
    "angelina jolie",
    "bungee jumping",
    "cherry blossom",
    "clothes hanger",
    "cookie monster",
    "fidget spinner",
    "jack-o-lantern",
    "morgan freeman",
    "mount rushmore",
    "sewing machine",
    "snowball fight",
    "susan wojcicki",
    "abraham lincoln",
    "air conditioner",
    "captain america",
    "charlie chaplin",
    "crash bandicoot",
    "electric guitar",
    "fitness trainer",
    "fred flintstone",
    "ice cream truck",
    "mark zuckerberg",
    "michael jackson",
    "nintendo switch",
    "northern lights",
    "procrastination",
    "sherlock holmes",
    "virtual reality",
    "william wallace",
    "winnie the pooh",
    "darwin watterson",
    "fashion designer",
    "flight attendant",
    "pencil sharpener",
    "phineas and ferb",
    "leonardo da vinci",
    "leonardo dicaprio",
    "statue of liberty",
    "sydney opera house",
    "leonardo di caprio",
    "william shakespeare"];

// Get the input field
var textInput = document.getElementById("word");

textInput.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    event.preventDefault();
    getWords()
  }
});

let countInput = document.getElementById("count");
countInput.addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
      event.preventDefault();
      count()
    }
});

function getWords() {
    let text = document.getElementById("word").value;
    text = text.toLowerCase();
    const len = text.length;
    sameLength = words.filter(word => word.length == len);

    // const regex = new RegExp(text.replace(/_/g, "\\w").replace(/ /g, "\\s"));
    const regex = new RegExp(text.replace(/_/g, ".").replace(/ /g, "\\s"));
    match = sameLength.filter(word => regex.test(word));

    // make at table of sameLength
    let table = "<table><tr><th>Sr.</th><th>Word</th></tr>";
    for (let i = 0; i < match.length; i++) {
        table += `<tr><td>${i}</td><td id = index${i} onclick="copyToClipboard('${match[i]}', ${i})">${match[i]}</td></tr>`;
    }
    table += "</table>";
    document.getElementById("output").innerHTML = table;
    // document.getElementById("output").innerHTML = text;
}

function count() {
    let count = document.getElementById("count").value;
    let countList = count.split(",");
    let len = countList.length;
    let word = "";
    for (let i = 0; i < len; i++) {
        let tamp = parseInt(countList[i]);
        word += "_".repeat(tamp);
        if (i != len - 1) {
            word += " ";
        }
    }
    document.getElementById("word").value = word;
    
}



function copyToClipboard(text, index) {
    var dummy = document.createElement("textarea");
    document.body.appendChild(dummy);
    dummy.value = text;
    dummy.select();
    document.execCommand("copy");
    document.body.removeChild(dummy);
    document.getElementById(`index${index}`).style.backgroundColor = "lightblue";
}
